from Practica2 import Equacio
print("")
print("200x - 50 = -78")
hghg = Equacio("200x - 50 = -78")
print("Resultat real: -0,14")
print("Resultat Script:")
hghg.calcula()
print("")

print("2x + 3 = 7")
hghg = Equacio("2x + 3 = 7.3")
print("Resultat real: 2.15")
print("Resultat Script:")
hghg.calcula()
print("")

print("53x + 8 = -65")
hghg = Equacio("53x + 8 = -65")
print("Resultat Real: -1,38")
print("Resultat Script:")
hghg.calcula()
print("")

print("75x - 45 = 652")
hghg = Equacio("75x - 45 = 652")
print("Resultat Real: 9,3")
print("Resultat Script:")
hghg.calcula()
print("")
